/** Single source of truth for Firestore collection names. */
export const COL = {
  users: "users",
  campuses: "campuses",
  memberships: "memberships",
  tribes: "tribes",
  clubs: "clubs",
  clubMemberships: "club_memberships",
  events: "events",
  eventQrSessions: "event_qr_sessions",
  rsvps: "rsvps",
  checkins: "checkins",
  eventFeedback: "event_feedback",
  coinLedger: "coin_ledger",
  coinBalances: "coin_balances",
  participationStats: "participation_stats",
  rewards: "rewards",
  redemptions: "redemptions",
  vendors: "vendors",
  referrals: "referrals",
  friendships: "friendships",
  brandAccounts: "brand_accounts",
  brandMemberships: "brand_memberships",
  quests: "quests",
  questCompletions: "quest_completions",
  notificationJobs: "notification_jobs",
  notificationDeliveryLogs: "notification_delivery_logs",
  surveys: "surveys",
  surveyResponses: "survey_responses",
  pilotMetrics: "pilot_metrics",
  metricsDaily: "metrics_daily",
  featureConfigs: "feature_configs",
  entitlements: "entitlements",
  auditLogs: "audit_logs",
  supportRequests: "support_requests",
  economyVersions: "economy_versions",
  analyticsEvents: "analytics_events",
  reports: "content_reports",
  tribeLeaderboards: "tribe_leaderboards",
  dataExports: "data_exports",
} as const;

export type CollectionName = (typeof COL)[keyof typeof COL];

/** Deterministic document id helpers (prevent duplicates by construction). */
export const ids = {
  membership: (campusId: string, uid: string) => `${campusId}_${uid}`,
  rsvp: (eventId: string, uid: string) => `${eventId}_${uid}`,
  checkin: (eventId: string, uid: string) => `${eventId}_${uid}`,
  feedback: (eventId: string, uid: string) => `${eventId}_${uid}`,
  friendship: (a: string, b: string) => [a, b].sort().join("_"),
  questCompletion: (questId: string, uid: string) => `${questId}_${uid}`,
  brandMembership: (brandId: string, uid: string) => `${brandId}_${uid}`,
  surveyResponse: (surveyId: string, uid: string) => `${surveyId}_${uid}`,
  metricsDaily: (campusId: string, isoDate: string) => `${campusId}_${isoDate}`,
  pilotMetrics: (campusId: string, weekKey: string) => `${campusId}_${weekKey}`,
  leaderboard: (campusId: string, weekKey: string) => `${campusId}_${weekKey}`,
  economyVersion: (campusId: string, version: number) => `${campusId}_v${version}`,
  ledger: {
    rsvp: (eventId: string, uid: string) => `rsvp:${eventId}:${uid}`,
    checkin: (eventId: string, uid: string) => `checkin:${eventId}:${uid}`,
    feedback: (eventId: string, uid: string) => `feedback:${eventId}:${uid}`,
    referral: (referredUid: string) => `referral:${referredUid}`,
    organizer: (eventId: string) => `organizer:${eventId}`,
    quest: (questId: string, uid: string) => `quest:${questId}:${uid}`,
    redemption: (redemptionId: string) => `redemption:${redemptionId}`,
    expiry: (creditKey: string) => `expiry:${creditKey}`,
    adjustment: (adjustmentId: string) => `adjustment:${adjustmentId}`,
  },
};
